### PR TITLE
Add settings view and local time preference

### PR DESCRIPTION
**Pull request by cak**
- Add settings view to More screen
   - Add setting to enable local time preference
- Adjust iPhone target to iOS 13 (for SwiftUI)

### CODE REVIEW

**Comment by theoriginalbit** [comment]
@sethlaw do you have any analytics data for device OS versions of the users?

Changing from iOS 10 to iOS 13 _just_ so SwiftUI can be used for a settings screen seems a bit crazy; that means that one screen which can _very_ easily be represented in UIKit has resulted in dropping support for 3 iOS versions.

**Comment by sethlaw** [comment]
Majority are iOS 13, but let me dig into firebase. I'll hold off on releasing until we know for sure. Can always switch tonight to UIKit and do the full transition after defcon.

**Comment by theoriginalbit** [comment]
> Majority are iOS 13, but let me dig into firebase.

Ah awesome.

> do the full transition after defcon.

So there are plans on rewriting the entire app to SwiftUI?

Just as a heads up, iOS 13's SwiftUI is not overly useful, there's a lot of pain points with it and a lot of things missing. iOS 14's SwiftUI (SwiftUI 2 as some are affectionately calling it) has fixed the vast majority of these issues and is much much much better, but not backward compatible.

**Comment by sethlaw** [comment]
So I was wrong, according the sources in App Store Analytics, we are split about 50/50 between 12 and 13. I'm gonna have @cak redo the Settings screen in UIKit for now and release with the updates. I was planning on going to SwiftUI, but if it's better in 14, may just limp along for another year until it's mostly adopted.

**Comment by sethlaw** [comment]
@theoriginalbit Would you like me to add you to the Testflight group for versions pushed to the App Store, would love to have your expertise/feedback on things as well.

**Comment by theoriginalbit** [comment]
> we are split about 50/50 between 12 and 13

Yeah that sounds like some people might have iPads that can't take iPadOS, which makes sense because iPadOS support was surprisingly limited compared to iOS. So all those iOS 12 installs might have something to do with people upgrading their phones more frequently than tablets and as a result their iPads are still in iOS land.

> I'm gonna have @cak redo the Settings screen in UIKit for now and release with the updates. I was planning on going to SwiftUI, but if it's better in 14, may just limp along for another year until it's mostly adopted.

Static table view in Interface Builder would be the quick fix for sure 👍

I'm sure iOS 15 will make SwiftUI even better, but at that point iOS 14 will be widely adopted and usable so SwiftUI all the things! I get the feeling that those iOS 14 features like home screen widgets would be amazing for this project, and they're definitely something that could be added even now as a conditional feature. iOS 14's SwiftUI also makes developing for other platforms like macOS and watchOS much nicer, so that's also something to look forward to doing.

> @theoriginalbit Would you like me to add you to the Testflight group for versions pushed to the App Store, would love to have your expertise/feedback on things as well.

Sure thing! I'd love to help 😊 email's on my GH profile

**Pull request merged**
