### PR TITLE
General cleanup. Add navbars to home and events tab.

### PR DESCRIPTION
**Pull request by chrsmys**
As you can see in the screenshots below, I have moved a lot of the core navigation over to be handled by NavigationControllers.  This decision was influenced by Apple's Human Interface Guidelines on modality (reference [here](https://developer.apple.com/ios/human-interface-guidelines/interaction/modality/)). 

simulator screen shot aug 18 2016 12 04 17 am

In the schedule view controller I have removed the filter buttons and made each day it's very own section in this list. The filter buttons felt kind of cramped on smaller devices, and on bigger devices the user would have to reach all the way to the top of the screen to change the day (this can be tough on the 6 plus). I believe this move will open up the possibility to give more context in the section name. For example, instead of saying Friday, it could say Today, Instead of Saturday the section title could say tomorrow. I feel like this is a big win, the conference days always seem to run together, and I forget what day it is. On top of giving more context to the user about the current conference day the TableView could also be automatically scrolled to the current conference day's section on load (HUGE time savers).

simulator screen shot aug 18 2016 12 04 24 am

simulator screen shot aug 18 2016 12 04 30 am

Please note: There is still a lot of work to be done on this. This PR is mainly to see if we are on the same page.

Thanks for your time.

### CODE REVIEW

**Comment by chrsmys** [comment]
Note: I also just fixed the vertical scrollview within vertical scrollview issue mentioned in issue #8 . This scrolling behavior feels a lot nicer on the 4s/5s and is a lot more predictable.

**Comment by sethlaw** [comment]
Great work, all stuff I wanted to get around to and you are beating me to it with work going on right now. Let me pull down and review, but looks good at first glance.

—Seth

**Comment by chrsmys** [comment]
Hey Seth,
Glad to hear you like it. I am planning on doing some more cleanup over the weekend.

**Comment by chrsmys** [comment]
@sethlaw Would you like me to keep adding to this PR, or can this be merged in?

**Comment by sethlaw** [comment]
Let me merge it, I pulled it down and tested most of it, just got pulled away on other things. I’ll try and wrap that up today.

**Pull request merged**
